# Generated by Django 5.0.7 on 2025-01-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technology",
            name="icon_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
