# Generated by Django 5.0.7 on 2025-01-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("issuer", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("link", models.URLField()),
                ("preview_image", models.URLField()),
            ],
        ),
    ]
