# Generated by Django 5.0.7 on 2025-01-01 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                (
                    "client_position",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "client_company",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("testimonial_text", models.TextField()),
                (
                    "client_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="client_photos/"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Highlight this testimonial on the homepage",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
