# Generated by Django 5.0.7 on 2025-01-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="client_photo",
        ),
        migrations.AddField(
            model_name="testimonial",
            name="client_photo_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
