# Generated by Django 5.0.7 on 2025-01-09 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimonials", "0002_alter_testimonial_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
