# Generated by Django 5.0.7 on 2025-01-01 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutPage",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="author",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="tags",
        ),
        migrations.DeleteModel(
            name="ContactMessage",
        ),
        migrations.DeleteModel(
            name="GithubRepo",
        ),
        migrations.DeleteModel(
            name="HomePage",
        ),
        migrations.DeleteModel(
            name="Resume",
        ),
        migrations.RemoveField(
            model_name="service",
            name="technologies",
        ),
        migrations.RemoveField(
            model_name="skills",
            name="category",
        ),
        migrations.DeleteModel(
            name="Testimonial",
        ),
        migrations.DeleteModel(
            name="BlogCategory",
        ),
        migrations.DeleteModel(
            name="BlogPost",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.DeleteModel(
            name="Technology",
        ),
        migrations.DeleteModel(
            name="Skills",
        ),
        migrations.DeleteModel(
            name="SkillsCategory",
        ),
    ]
