# Generated by Django 5.0.7 on 2025-01-20 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resume",
            options={"verbose_name": "Resume", "verbose_name_plural": "Resumes"},
        ),
        migrations.RemoveField(
            model_name="resume",
            name="resume_file",
        ),
        migrations.AddField(
            model_name="resume",
            name="resume_format",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("docx", "DOCX")],
                default="pdf",
                max_length=4,
                verbose_name="Resume Format",
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date Created"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="resume_url",
            field=models.URLField(verbose_name="Resume URL"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Resume Title"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Date Updated"),
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(
                fields=["resume_url"], name="resume_resu_resume__39d4eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(
                fields=["resume_format"], name="resume_resu_resume__25b704_idx"
            ),
        ),
    ]
