# Generated by Django 5.0.7 on 2025-01-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubrepo",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="githubrepo",
            name="video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
