# Generated by Django 5.0.7 on 2025-01-01 08:35

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("inquiry", "General Inquiry"),
                            ("hire", "Hire"),
                            ("support", "Support Request"),
                            ("collaboration", "Collaboration"),
                            ("other", "Other"),
                        ],
                        default="inquiry",
                        max_length=20,
                    ),
                ),
                (
                    "other_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["sent_at"], name="contact_con_sent_at_32f86f_idx"
                    ),
                    models.Index(fields=["read"], name="contact_con_read_17e120_idx"),
                ],
            },
        ),
    ]
