# Generated by Django 5.0.7 on 2025-01-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mission_statement", models.TextField()),
                ("values", models.TextField()),
                ("history", models.TextField()),
                (
                    "team_members",
                    models.JSONField(
                        default=dict, help_text="List of team members with details."
                    ),
                ),
                (
                    "contact_info",
                    models.JSONField(default=dict, help_text="Contact Information."),
                ),
                (
                    "social_links",
                    models.JSONField(default=dict, help_text="Social media links."),
                ),
            ],
        ),
    ]
