# Generated by Django 5.0.7 on 2025-01-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("introduction", models.TextField()),
                (
                    "header_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "header_subtitle",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                ("professional_summary", models.TextField(blank=True, null=True)),
                ("call_to_action", models.URLField()),
                ("contact_info", models.JSONField(blank=True, null=True)),
                ("social_links", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
